### ISSUE TITLE
Handle failed `POST /migrate-configuration` calls

### ISSUE THREAD

**Issue by romantmb** [keboola/app-project-migrate#45]
Tady se možná objeví jedna věc, kterou jsme úplně nedořešili - pokud se ta migrace kousne/spadne, tak se tenhle loop spustí znovu a ty existující konfigurace vyfailují. Teď bych to tak asi nechal, ale pokud by se to ukázalo jako velkej problém, tak to bude chtít aby ten migrační endpoint vrátil nějakou chybu a umělo to zmigrovat jen konfigurace, který neexistují. Ale zatím bych to nedělal

_Originally posted by @odinuv in https://github.com/keboola/app-project-migrate/pull/43#discussion_r1595565295_

**Comment by odinuv** [comment]
Issue jsem myslel do Jiry, ne Githubu
